#[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "target-feature=+crt-static"]

#[target.x86_64-pc-windows-gnu]
#rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static", "-C", "link-arg=-static-libgcc"]

[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static",
    "-C", "link-arg=-static-libgcc",
    "-C", "link-arg=-Wl,--subsystem,windows:6.1",
    "-C", "link-arg=-Wl,--major-os-version=6",
    "-C", "link-arg=-Wl,--minor-os-version=1"
]